name: CI

on:
  push:
    branches:
      - master
      - demo
  pull_request:
    branches:
      - master
      - demo

jobs:
  section_07_test_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tests
        run: tox
        working-directory: section-07-ci-and-publishing/house-prices-api

  section_07_deploy_app_to_railway:
    needs: section_07_test_app
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 16.13
        uses: actions/setup-node@v2
        with:
          node-version: 16.13
      - name: Install Railway CLI
        run: npm i -g @railway/cli
      - name: Deploy to Railway App
        run: railway up --detach --service ${{ secrets.RAILWAY_SERVICE_ID }}
        working-directory: section-07-ci-and-publishing/house-prices-api
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  section_08_deploy_app_container_via_railway:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.2.0
        with:
          build-args: PIP_EXTRA_INDEX_URL=${{ secrets.PIP_EXTRA_INDEX_URL }}
          context: ./section-08-deploying-with-containers
          push: false
      - name: Set up Node.js 16.13
        uses: actions/setup-node@v2
        with:
          node-version: 16.13
      - name: Install Railway CLI
        run: npm i -g @railway/cli
      - name: Deploy to Railway App
        run: railway up --detach --service ${{ secrets.RAILWAY_SERVICE_ID }}
        working-directory: section-08-deploying-with-containers
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
